import "dotenv/config";
import mongoose from "mongoose";
import Product from "../src/models/Product.js";
import Category from "../src/models/Category.js";

await mongoose.connect(process.env.MONGO_URI);
console.log("Conectado a MongoDB");

await Product.deleteMany({});
await Category.deleteMany({});
console.log("Datos anteriores eliminados");

const categorias = await Category.insertMany([
  { nombre: "Vestidos", urlNombre: "vestidos" },
  { nombre: "Trajes", urlNombre: "trajes" },
  { nombre: "Camisas", urlNombre: "camisas" },
  { nombre: "Pantalones", urlNombre: "pantalones" },
  { nombre: "Zapatos", urlNombre: "zapatos" },
  { nombre: "Cintos", urlNombre: "cintos" },
  { nombre: "Relojes", urlNombre: "relojes" },
  { nombre: "Accesorios", urlNombre: "accesorios" },
]);
console.log(`${categorias.length} categorías insertadas`);

function getCategoriaId(urlNombre) {
  const categoria = categorias.find((c) => c.urlNombre === urlNombre);
  return categoria._id;
}

const productos = await Product.insertMany([
  {
    nombre: "Vestido Noche Noir",
    descripcion: "Vestido largo de seda negra con escote en V y espalda descubierta. Ideal para eventos de gala.",
    precio: 89900,
    precioAnterior: 120000,
    imagenes: ["https://images.pexels.com/photos/37094152/pexels-photo-37094152.jpeg"],
    categoria: getCategoriaId("vestidos"),
    stock: 8,
    talle: ["XS", "S", "M", "L"],
    color: ["Negro"],
    genero: "mujer",
    material: "Seda",
    destacado: true,
    urlNombre: "vestido-noche-noir",
  },
  {
    nombre: "Vestido Midi Ivory",
    descripcion: "Vestido midi de encaje marfil con manga tres cuartos. Elegancia atemporal para ocasiones especiales.",
    precio: 74500,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/18953352/pexels-photo-18953352.jpeg"],
    categoria: getCategoriaId("vestidos"),
    stock: 5,
    talle: ["XS", "S", "M"],
    color: ["Marfil"],
    genero: "mujer",
    material: "Encaje",
    destacado: false,
    urlNombre: "vestido-midi-ivory",
  },
  {
    nombre: "Vestido Rojo Pasión",
    descripcion: "Vestido corto de crepé rojo intenso con corte asimétrico y detalle en el hombro.",
    precio: 68000,
    precioAnterior: 85000,
    imagenes: ["https://images.pexels.com/photos/29850959/pexels-photo-29850959.jpeg"],
    categoria: getCategoriaId("vestidos"),
    stock: 6,
    talle: ["S", "M", "L"],
    color: ["Rojo"],
    genero: "mujer",
    material: "Crepé",
    destacado: true,
    urlNombre: "vestido-rojo-pasion",
  },
  {
    nombre: "Traje Clásico Onyx",
    descripcion: "Traje de dos piezas en lana merino negro. Corte italiano slim fit con solapa de punta.",
    precio: 185000,
    precioAnterior: 220000,
    imagenes: ["https://images.pexels.com/photos/33290975/pexels-photo-33290975.jpeg"],
    categoria: getCategoriaId("trajes"),
    stock: 4,
    talle: ["S", "M", "L", "XL"],
    color: ["Negro"],
    genero: "hombre",
    material: "Lana merino",
    destacado: true,
    urlNombre: "traje-clasico-onyx",
  },
  {
    nombre: "Traje Gris Perla",
    descripcion: "Traje slim fit en gabardina gris perla. Incluye chaleco y pantalón a juego.",
    precio: 210000,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/34299170/pexels-photo-34299170.jpeg"],
    categoria: getCategoriaId("trajes"),
    stock: 3,
    talle: ["M", "L", "XL"],
    color: ["Gris"],
    genero: "hombre",
    material: "Gabardina",
    destacado: false,
    urlNombre: "traje-gris-perla",
  },
  {
    nombre: "Traje Azul Noche",
    descripcion: "Traje de corte moderno en lana azul marino con forro interior estampado.",
    precio: 195000,
    precioAnterior: 240000,
    imagenes: ["https://images.pexels.com/photos/31316858/pexels-photo-31316858.jpeg"],
    categoria: getCategoriaId("trajes"),
    stock: 5,
    talle: ["S", "M", "L", "XL", "XXL"],
    color: ["Azul marino"],
    genero: "hombre",
    material: "Lana",
    destacado: true,
    urlNombre: "traje-azul-noche",
  },
  {
    nombre: "Camisa Oxford Blanca",
    descripcion: "Camisa de algodón Oxford blanco con puños dobles. Confección a mano con botones de nácar.",
    precio: 32000,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/27373532/pexels-photo-27373532.jpeg"],
    categoria: getCategoriaId("camisas"),
    stock: 15,
    talle: ["S", "M", "L", "XL", "XXL"],
    color: ["Blanco"],
    genero: "hombre",
    material: "Algodón Oxford",
    destacado: false,
    urlNombre: "camisa-oxford-blanca",
  },
  {
    nombre: "Camisa Seda Celeste",
    descripcion: "Camisa de seda celeste de corte regular. Ideal para combinar con traje o pantalón de vestir.",
    precio: 47000,
    precioAnterior: 58000,
    imagenes: ["https://images.pexels.com/photos/20636340/pexels-photo-20636340.jpeg"],
    categoria: getCategoriaId("camisas"),
    stock: 10,
    talle: ["S", "M", "L", "XL"],
    color: ["Celeste"],
    genero: "hombre",
    material: "Seda",
    destacado: true,
    urlNombre: "camisa-seda-celeste",
  },
  {
    nombre: "Camisa Lino Beige",
    descripcion: "Camisa de lino beige de manga larga. Liviana y transpirable para eventos diurnos.",
    precio: 28500,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/22441291/pexels-photo-22441291.jpeg"],
    categoria: getCategoriaId("camisas"),
    stock: 12,
    talle: ["S", "M", "L", "XL", "XXL"],
    color: ["Beige"],
    genero: "unisex",
    material: "Lino",
    destacado: false,
    urlNombre: "camisa-lino-beige",
  },
  {
    nombre: "Pantalón Vestir Negro",
    descripcion: "Pantalón de vestir en gabardina negra con pinzas. Corte recto clásico con cierre invisible.",
    precio: 42000,
    precioAnterior: 52000,
    imagenes: ["https://images.pexels.com/photos/7999002/pexels-photo-7999002.jpeg"],
    categoria: getCategoriaId("pantalones"),
    stock: 10,
    talle: ["S", "M", "L", "XL"],
    color: ["Negro"],
    genero: "hombre",
    material: "Gabardina",
    destacado: false,
    urlNombre: "pantalon-vestir-negro",
  },
  {
    nombre: "Pantalón Palazzo Crema",
    descripcion: "Pantalón palazzo de crepé crema de tiro alto. Amplitud y elegancia en cada movimiento.",
    precio: 38000,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/7143497/pexels-photo-7143497.jpeg"],
    categoria: getCategoriaId("pantalones"),
    stock: 7,
    talle: ["XS", "S", "M", "L"],
    color: ["Crema"],
    genero: "mujer",
    material: "Crepé",
    destacado: true,
    urlNombre: "pantalon-palazzo-crema",
  },
  {
    nombre: "Pantalón Lana Gris",
    descripcion: "Pantalón de lana gris marengo con dobladillo y cinto incluido. Ideal para traje o blazer.",
    precio: 55000,
    precioAnterior: 68000,
    imagenes: ["https://hussars.net/cdn/shop/files/PANTALONESgrises.jpg?v=1742730401&width=1960"],
    categoria: getCategoriaId("pantalones"),
    stock: 9,
    talle: ["S", "M", "L", "XL", "XXL"],
    color: ["Gris"],
    genero: "hombre",
    material: "Lana",
    destacado: false,
    urlNombre: "pantalon-lana-gris",
  },
  {
    nombre: "Zapato Oxford Cuero Negro",
    descripcion: "Zapato Oxford de cuero genuino negro con suela de cuero y costura Blake. Hecho a mano.",
    precio: 98000,
    precioAnterior: 125000,
    imagenes: ["https://images.pexels.com/photos/15557052/pexels-photo-15557052.jpeg"],
    categoria: getCategoriaId("zapatos"),
    stock: 6,
    talle: ["S", "M", "L"],
    color: ["Negro"],
    genero: "hombre",
    material: "Cuero genuino",
    destacado: true,
    urlNombre: "zapato-oxford-cuero-negro",
  },
  {
    nombre: "Stiletto Nude",
    descripcion: "Stiletto de cabritilla nude con taco de 10cm y puntera fina. Sofisticación en cada paso.",
    precio: 76000,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/27035625/pexels-photo-27035625.jpeg"],
    categoria: getCategoriaId("zapatos"),
    stock: 5,
    talle: ["XS", "S", "M"],
    color: ["Nude"],
    genero: "mujer",
    material: "Cabritilla",
    destacado: true,
    urlNombre: "stiletto-nude",
  },
  {
    nombre: "Mocasín Borla Marrón",
    descripcion: "Mocasín de cuero marrón con detalle de borla dorada. Comfort y distinción para el día a día formal.",
    precio: 82000,
    precioAnterior: 99000,
    imagenes: ["https://images.pexels.com/photos/18689007/pexels-photo-18689007.jpeg"],
    categoria: getCategoriaId("zapatos"),
    stock: 8,
    talle: ["S", "M", "L", "XL"],
    color: ["Marrón"],
    genero: "hombre",
    material: "Cuero",
    destacado: false,
    urlNombre: "mocasin-borla-marron",
  },
  {
    nombre: "Cinto Cuero Cocodrilo Negro",
    descripcion: "Cinto de cuero texturizado símil cocodrilo negro con hebilla dorada. Ancho 3cm.",
    precio: 28000,
    precioAnterior: 35000,
    imagenes: ["https://images.pexels.com/photos/35392711/pexels-photo-35392711.jpeg"],
    categoria: getCategoriaId("cintos"),
    stock: 14,
    talle: ["S", "M", "L", "XL"],
    color: ["Negro"],
    genero: "hombre",
    material: "Cuero",
    destacado: false,
    urlNombre: "cinto-cuero-cocodrilo-negro",
  },
  {
    nombre: "Cinto Finesse Nude",
    descripcion: "Cinto fino de cuero nude con hebilla plateada minimal. Perfecto para vestidos y pantalones de tiro alto.",
    precio: 22000,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/21053488/pexels-photo-21053488.jpeg"],
    categoria: getCategoriaId("cintos"),
    stock: 11,
    talle: ["XS", "S", "M"],
    color: ["Nude"],
    genero: "mujer",
    material: "Cuero",
    destacado: false,
    urlNombre: "cinto-finesse-nude",
  },
  {
    nombre: "Reloj Chronos Noir",
    descripcion: "Reloj automático con caja de acero inoxidable negro, esfera minimalista y correa de cuero genuino.",
    precio: 320000,
    precioAnterior: 390000,
    imagenes: ["https://images.pexels.com/photos/10414981/pexels-photo-10414981.jpeg"],
    categoria: getCategoriaId("relojes"),
    stock: 3,
    talle: [],
    color: ["Negro", "Plateado"],
    genero: "unisex",
    material: "Acero inoxidable",
    destacado: true,
    urlNombre: "reloj-chronos-noir",
  },
  {
    nombre: "Reloj Élite Gold",
    descripcion: "Reloj de cuarzo con caja chapada en oro 18k, esfera nacarada y brazalete de acero.",
    precio: 485000,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/9203637/pexels-photo-9203637.jpeg"],
    categoria: getCategoriaId("relojes"),
    stock: 2,
    talle: [],
    color: ["Dorado"],
    genero: "mujer",
    material: "Acero chapado en oro",
    destacado: true,
    urlNombre: "reloj-elite-gold",
  },
  {
    nombre: "Reloj Clásico Plata",
    descripcion: "Reloj de cuerda manual con caja de plata 925, esfera romana y correa de cuero marrón.",
    precio: 275000,
    precioAnterior: 310000,
    imagenes: ["https://images.pexels.com/photos/36812419/pexels-photo-36812419.jpeg"],
    categoria: getCategoriaId("relojes"),
    stock: 4,
    talle: [],
    color: ["Plateado", "Marrón"],
    genero: "hombre",
    material: "Plata 925",
    destacado: false,
    urlNombre: "reloj-clasico-plata",
  },
  {
    nombre: "Pañuelo Seda Estampado",
    descripcion: "Pañuelo de seda estampado 90x90cm. Diseño floral exclusivo de la colección primavera.",
    precio: 18500,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/3204622/pexels-photo-3204622.jpeg"],
    categoria: getCategoriaId("accesorios"),
    stock: 20,
    talle: [],
    color: ["Multicolor"],
    genero: "mujer",
    material: "Seda",
    destacado: false,
    urlNombre: "panuelo-seda-estampado",
  },
  {
    nombre: "Cartera Clutch Dorada",
    descripcion: "Clutch minaudière dorada con cierre magnético y cadena removible. Capacidad para teléfono y esenciales.",
    precio: 54000,
    precioAnterior: 67000,
    imagenes: ["https://images.pexels.com/photos/15853506/pexels-photo-15853506.jpeg"],
    categoria: getCategoriaId("accesorios"),
    stock: 7,
    talle: [],
    color: ["Dorado"],
    genero: "mujer",
    material: "Metal y cuero",
    destacado: true,
    urlNombre: "cartera-clutch-dorada",
  },
  {
    nombre: "Corbata Seda Burdeos",
    descripcion: "Corbata de seda pura burdeos con textura subtle. Ancho clásico 8cm. Confeccionada en Italia.",
    precio: 24000,
    precioAnterior: null,
    imagenes: ["https://images.pexels.com/photos/35839968/pexels-photo-35839968.jpeg"],
    categoria: getCategoriaId("accesorios"),
    stock: 16,
    talle: [],
    color: ["Burdeos"],
    genero: "hombre",
    material: "Seda",
    destacado: false,
    urlNombre: "corbata-seda-burdeos",
  },
  {
    nombre: "Gemelos Plata Grabados",
    descripcion: "Gemelos de plata 925 con grabado geométrico art déco. Presentados en estuche de regalo.",
    precio: 42000,
    precioAnterior: 55000,
    imagenes: ["https://images.pexels.com/photos/11745260/pexels-photo-11745260.jpeg"],
    categoria: getCategoriaId("accesorios"),
    stock: 9,
    talle: [],
    color: ["Plateado"],
    genero: "hombre",
    material: "Plata 925",
    destacado: true,
    urlNombre: "gemelos-plata-grabados",
  },
]);
console.log(`${productos.length} productos insertados`);

await mongoose.disconnect();
console.log("Listo!");
